name: memplato_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.7+2

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  flutter_client_sse: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/memplato_server.py
    - assets/model.onnx
    - assets/tokenizer.json
    - assets/tokenizer_config.json
    - assets/vocab.txt
    - assets/python_deps/
    - assets/wheels/